spring:
  datasource:
    postgresql:
      url: jdbc:postgresql://localhost:55432/example
      username: example_user
      password: example_password
      driver-class-name: org.postgresql.Driver
    mysql:
      url: jdbc:mysql://localhost:53306/example
      username: example_user
      password: example_password
      driver-class-name: com.mysql.cj.jdbc.Driver